/*
 * ---metadata---
 * type: package-source
 * description: Landscape Character Assessment draft generation and layer mapping for Landschaft.
 * last-updated: 2026-06-28
 * last-model: composer
 * last-change: add mock LCA draft generator and coded area layer writer
 * ---end-metadata---
 */
import type {
  CodedArea,
  Coordinate,
  MapWriteDraftRequest,
  PlanningLayer,
  ProjectMetadata,
  ReviewStatus,
  VectorFeature
} from "./index.js";
import type { MapEvidenceFeature, MapReadResult } from "./mapEvidence.js";

export interface LcaDraftAnalysisRequest {
  purpose: string;
  evidence: MapReadResult;
}

export interface LcaDraftAnalysisResult {
  areas: CodedArea[];
  model: string;
  promptVersion: string;
  inputLayerIds: string[];
}

export interface MapWriteDraftResult {
  status: "draft-written";
  projectId: string;
  targetLayerId: string;
  layer: PlanningLayer;
  featureCount: number;
  reviewStatus: ReviewStatus;
  reason: string;
}

const LCA_LAYER_ID = "landscape-character-assessment";
const LCA_PROMPT_VERSION = "lca-mvp-v1";

export function generateLcaCodedId() {
  const alphabet = "abcdefghijklmnopqrstuvwxyz0123456789";
  return Array.from({ length: 10 }, () => {
    const index = Math.floor(Math.random() * alphabet.length);
    return alphabet[index];
  }).join("");
}

export function generateMockLcaDraft(
  request: LcaDraftAnalysisRequest
): LcaDraftAnalysisResult {
  const polygonFeatures = request.evidence.features.filter(
    (feature) => feature.geometryType === "polygon" && feature.coordinates.length >= 3
  );

  const areas =
    polygonFeatures.length > 0
      ? polygonFeatures.slice(0, 4).map((feature, index) =>
          codedAreaFromEvidenceFeature(feature, request.purpose, index)
        )
      : defaultExtentCharacterAreas(request.evidence, request.purpose);

  return {
    areas,
    model: "landschaft-mock-lca",
    promptVersion: LCA_PROMPT_VERSION,
    inputLayerIds: request.evidence.selectedLayerIds
  };
}

export function createLcaLayerFromDraft(
  project: ProjectMetadata,
  areas: CodedArea[],
  analysis: Pick<LcaDraftAnalysisResult, "model" | "promptVersion" | "inputLayerIds">
): PlanningLayer {
  const features = areas.map((area) => codedAreaToVectorFeature(area, analysis));

  return {
    id: LCA_LAYER_ID,
    name: "Landscape Character Assessment",
    kind: "lca",
    visible: true,
    opacity: 0.82,
    reviewStatus: "needs-review",
    category: "designer-created",
    geometryType: "polygon",
    source: {
      sourceName: "LCA draft analysis",
      sourceType: "derived",
      sourceDate: new Date().toISOString().slice(0, 10),
      coordinateReferenceSystem: project.coordinateReferenceSystem,
      accuracyStatus: "provider-derived",
      confidence: averageConfidence(areas)
    },
    style: {
      stroke: "#5f4b8b",
      fill: "#9d8ec7",
      strokeWidth: 2
    },
    legend: areas.map((area) => ({
      label: area.label,
      color: "#9d8ec7"
    })),
    features,
    planningImpactNotes: [
      "Draft landscape character areas require human review before planning use.",
      `Generated by ${analysis.model} using prompt ${analysis.promptVersion}.`
    ],
    locked: false
  };
}

export function applyMapWriteDraft(
  project: ProjectMetadata,
  request: MapWriteDraftRequest,
  existingLayers: PlanningLayer[],
  analysisMeta?: Pick<LcaDraftAnalysisResult, "model" | "promptVersion" | "inputLayerIds">
): MapWriteDraftResult {
  const validatedAreas = request.features.map(validateCodedArea);
  const existingLayer = existingLayers.find(
    (layer) => layer.id === (request.targetLayerId ?? LCA_LAYER_ID)
  );
  const layer = createLcaLayerFromDraft(project, validatedAreas, {
    model: analysisMeta?.model ?? "external-llm",
    promptVersion: analysisMeta?.promptVersion ?? LCA_PROMPT_VERSION,
    inputLayerIds:
      analysisMeta?.inputLayerIds ??
      existingLayer?.features?.map((feature) => feature.id) ??
      []
  });

  if (request.createLayerName) {
    layer.name = request.createLayerName;
  }

  return {
    status: "draft-written",
    projectId: request.projectId,
    targetLayerId: layer.id,
    layer,
    featureCount: layer.features?.length ?? 0,
    reviewStatus: layer.reviewStatus,
    reason: request.reason
  };
}

function codedAreaFromEvidenceFeature(
  feature: MapEvidenceFeature,
  purpose: string,
  index: number
): CodedArea {
  return {
    id: generateLcaCodedId(),
    label: feature.label || `Character Area ${index + 1}`,
    ring: closeRing(feature.coordinates),
    layer: "lca",
    code: deriveCharacterCode(feature.attributes),
    meaning: buildCharacterMeaning(feature, purpose),
    confidence: clampConfidence(0.66 + index * 0.05)
  };
}

function defaultExtentCharacterAreas(
  evidence: MapReadResult,
  purpose: string
): CodedArea[] {
  const { width, depth } = evidence.projectExtent;
  const northMeaning = `Northern project character derived from selected layers for ${purpose}.`;
  const southMeaning = `Southern project character derived from selected layers for ${purpose}.`;

  return [
    {
      id: generateLcaCodedId(),
      label: "North character area",
      ring: closeRing([
        [0, 0],
        [width * 0.52, 0],
        [width * 0.48, depth * 0.56],
        [0, depth * 0.5],
        [0, 0]
      ]),
      layer: "lca",
      code: "N-CH",
      meaning: northMeaning,
      confidence: 0.62
    },
    {
      id: generateLcaCodedId(),
      label: "South character area",
      ring: closeRing([
        [width * 0.48, depth * 0.44],
        [width, depth * 0.5],
        [width, depth],
        [0, depth],
        [width * 0.48, depth * 0.44]
      ]),
      layer: "lca",
      code: "S-CH",
      meaning: southMeaning,
      confidence: 0.6
    }
  ];
}

function codedAreaToVectorFeature(
  area: CodedArea,
  analysis: Pick<LcaDraftAnalysisResult, "model" | "promptVersion" | "inputLayerIds">
): VectorFeature {
  return {
    id: area.id,
    label: area.label,
    geometryType: "polygon",
    coordinates: openRing(area.ring),
    attributes: {
      lcaCodedId: area.id,
      characterCode: area.code,
      reviewStatus: "needs-review",
      confidence: String(area.confidence),
      model: analysis.model,
      promptVersion: analysis.promptVersion,
      inputLayerIds: analysis.inputLayerIds.join(","),
      meaning: area.meaning
    },
    planningImpact:
      "Review this landscape character area against source layers before using it in planning."
  };
}

function validateCodedArea(area: CodedArea): CodedArea {
  if (area.ring.length < 4) {
    throw new Error(`Coded area ${area.id} must contain at least four coordinates.`);
  }

  return {
    ...area,
    ring: closeRing(area.ring),
    confidence: clampConfidence(area.confidence)
  };
}

function deriveCharacterCode(attributes: Record<string, string>) {
  const soil = attributes.soil ?? attributes.Soil;
  const drainage = attributes.drainage ?? attributes.Drainage;
  const landUse = attributes.landUse ?? attributes.suitability ?? attributes.LandUse;

  return [soil, drainage, landUse]
    .filter(Boolean)
    .map((value) => value.slice(0, 2).toUpperCase())
    .join("")
    .slice(0, 6) || "LCA";
}

function buildCharacterMeaning(feature: MapEvidenceFeature, purpose: string) {
  const attributeSummary = Object.entries(feature.attributes)
    .slice(0, 4)
    .map(([key, value]) => `${key}: ${value}`)
    .join("; ");

  return attributeSummary
    ? `${feature.label} contributes to ${purpose}. Evidence: ${attributeSummary}.`
    : `${feature.label} contributes to ${purpose} based on mapped project evidence.`;
}

function closeRing(coordinates: Coordinate[]): Coordinate[] {
  if (coordinates.length === 0) {
    return coordinates;
  }

  const first = coordinates[0];
  const last = coordinates[coordinates.length - 1];
  if (first[0] === last[0] && first[1] === last[1]) {
    return coordinates;
  }

  return [...coordinates, first];
}

function openRing(ring: Coordinate[]): Coordinate[] {
  if (ring.length < 2) {
    return ring;
  }

  const first = ring[0];
  const last = ring[ring.length - 1];
  if (first[0] === last[0] && first[1] === last[1]) {
    return ring.slice(0, -1);
  }

  return ring;
}

function averageConfidence(areas: CodedArea[]) {
  if (areas.length === 0) {
    return 0.5;
  }

  return areas.reduce((total, area) => total + area.confidence, 0) / areas.length;
}

function clampConfidence(value: number) {
  return Math.min(Math.max(value, 0), 1);
}
